@cardanosolutions/json-bigint based implementation
mlabs-haskell/purescript-aeson pull request #13
Opened 2022-11-30 17:53 UTC by kirill-havryliuk

Full rework of library. Breaking changes. 

As for now it is based on json-bigint (#11 ).

Internally, our json representation (Aeson) relies on BigNumber from bignumber.js, to represent numbers.
This allows us deserialize/serialize JSONs holding arbitrary size numbers, including numbers with floating point.

2022-12-01 12:26 UTC, klntsky requested changes

2022-12-01 12:46 UTC, uhbif19 commented
https://github.com/mlabs-haskell/purescript-aeson/issues/12 will be probably closed too by this PR.

2022-12-03 07:07 UTC, uhbif19 requested changes

2022-12-03 07:07 UTC, uhbif19 commented on src/Aeson.purs
> +-- decodeNumber ∷ ∀ a. (String → Maybe a) -> String -> Aeson -> Either JsonDecodeError a
Commented code.

2022-12-03 07:07 UTC, uhbif19 commented on src/Aeson.purs
> +-- | Uses json-bigint library to parse JSON.
```suggestion
-- | Uses `json-bigint` library to parse JSON.
```

2022-12-03 07:51 UTC, uhbif19 commented
@klntsky @kirill-havryliuk Resolved already covered comments.

2022-12-05 11:40 UTC, klntsky requested changes
Same everywhere where applicable

2022-12-05 11:40 UTC, klntsky commented on src/Aeson.purs
> +toStringifiedNumbersJson = defer $ \_ -> caseAeson
```suggestion
toStringifiedNumbersJson = defer \_ -> caseAeson
```

2022-12-05 11:40 UTC, klntsky commented on src/Aeson.purs
> +toStringifiedNumbersJson = defer $ \_ -> caseAeson
https://github.com/Plutonomicon/cardano-transaction-lib/issues/56#issue-1116215499

2022-12-12 22:16 UTC, uhbif19 commented
@klntsky @kirill-havryliuk Looks like all issues resolved, no? Merge it?

2022-12-13 02:46 UTC, kirill-havryliuk commented
> @klntsky @kirill-havryliuk Looks like all issues resolved, no? Merge it?

@uhbif19 I would like to refactor CTL so it is based on this version first, so if we miss something we still can add it here, and not introduce new PR.

2022-12-14 14:57 UTC, uhbif19 commented on src/Aeson.purs
> +-- | The reson we return `Finite BigNumber` instead of a plain `BigNumber`,
```suggestion
-- | The reason we return `Finite BigNumber` instead of a plain `BigNumber`,
```

2022-12-14 15:06 UTC, uhbif19 commented on src/Aeson.js
> +// _caseAeson
Do not understand what happened.

2022-12-14 16:28 UTC, klntsky commented on test/Gen.purs
> +  -- forceSign <- arbitrary
Leftover?

2022-12-14 16:28 UTC, klntsky commented on test/Gen.purs
> +      -- sign = if negSign then "-" else when forceSign "+"
Leftover?

2022-12-14 16:53 UTC, klntsky approved these changes

2022-12-14 16:53 UTC, merged